# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23ab482a78b3916e0dd4aae2701e495550ef415e824c12f77820692d63c051581624d54090aa1e3bc58fe4658a0fc65cbcc612dd70cba643bce404d356851fe1

test:
  secret_key_base: b246bfaf361a78d32f2965bdada6b89d2c1166e1cec2ff67f1d717bc7037f7d982ba4e8d5a4bd44eaab987eef1328acd7cba4aeb53b4c9d3d7df48b2d9bb1971

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
